# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Child.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildWindow(object):
    def setupUi(self, ChildWindow):
        ChildWindow.setObjectName("ChildWindow")
        ChildWindow.resize(546, 774)
        ChildWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ChildWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Data_Table = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.Data_Table.setFont(font)
        self.Data_Table.setStyleSheet("")
        self.Data_Table.setLineWidth(1)
        self.Data_Table.setObjectName("Data_Table")
        self.Data_Table.setColumnCount(0)
        self.Data_Table.setRowCount(0)
        self.horizontalLayout.addWidget(self.Data_Table)
        ChildWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChildWindow)
        self.statusbar.setObjectName("statusbar")
        ChildWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChildWindow)
        QtCore.QMetaObject.connectSlotsByName(ChildWindow)

    def retranslateUi(self, ChildWindow):
        _translate = QtCore.QCoreApplication.translate
        ChildWindow.setWindowTitle(_translate("ChildWindow", "数据显示"))
