# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test011.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 870)
        MainWindow.setBaseSize(QtCore.QSize(1200, 0))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/background/logo.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow{border-image: url(:/background/jianyue.jpg);}\n"
"")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_vedio = QtWidgets.QLabel(self.centralwidget)
        self.label_vedio.setMinimumSize(QtCore.QSize(650, 750))
        self.label_vedio.setStyleSheet("QLabel{border-image: url(:/background/xiaohui.png);}\n"
"")
        self.label_vedio.setText("")
        self.label_vedio.setObjectName("label_vedio")
        self.horizontalLayout.addWidget(self.label_vedio)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(450, 800))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 850))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox{background-color: rgba(247, 252, 254,180);}\n"
"\n"
"\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 390, 401, 211))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{background-color: rgba(42, 221, 156,0);}\n"
"")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_name = QtWidgets.QLabel(self.groupBox)
        self.label_name.setGeometry(QtCore.QRect(23, 33, 105, 30))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("")
        self.label_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name.setLineWidth(1)
        self.label_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_name.setObjectName("label_name")
        self.lineEdit_Name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Name.setGeometry(QtCore.QRect(110, 30, 271, 41))
        self.lineEdit_Name.setStyleSheet("border:1px solid rgb(12, 137, 24);\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_Name.setText("")
        self.lineEdit_Name.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.label_proj = QtWidgets.QLabel(self.groupBox)
        self.label_proj.setGeometry(QtCore.QRect(20, 80, 105, 30))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_proj.setFont(font)
        self.label_proj.setObjectName("label_proj")
        self.lineEdit_Proj = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Proj.setGeometry(QtCore.QRect(110, 80, 271, 41))
        self.lineEdit_Proj.setStyleSheet("border:1px solid rgb(12, 137, 24);\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_Proj.setObjectName("lineEdit_Proj")
        self.label_num = QtWidgets.QLabel(self.groupBox)
        self.label_num.setGeometry(QtCore.QRect(20, 130, 105, 30))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.label_num.setFont(font)
        self.label_num.setObjectName("label_num")
        self.lineEdit_Num = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Num.setGeometry(QtCore.QRect(110, 130, 271, 41))
        self.lineEdit_Num.setStyleSheet("border:1px solid rgb(12, 137, 24);\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_Num.setObjectName("lineEdit_Num")
        self.label_infor_tips = QtWidgets.QLabel(self.groupBox)
        self.label_infor_tips.setGeometry(QtCore.QRect(20, 180, 361, 20))
        self.label_infor_tips.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 85, 0);\n"
"")
        self.label_infor_tips.setObjectName("label_infor_tips")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(60, 180, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:2px solid  rgba(68, 206, 246,150);\n"
"background-color: rgba(102, 204, 204,180);\n"
"border-radius:15px; \n"
"color: rgb(0, 51, 113);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:2px solid  rgba(14, 184, 58,150);\n"
"}\n"
"QPushButton:pressed{padding-top:2px;\n"
"padding-left:2px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_submit = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_submit.setGeometry(QtCore.QRect(40, 750, 391, 61))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(22)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_submit.setStyleSheet("QPushButton{\n"
"border:2px solid  rgba(68, 206, 246,150);\n"
"background-color: rgba(102, 204, 204,180);\n"
"border-radius:15px; \n"
"color: rgb(0, 51, 113);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:2px solid  rgba(14, 184, 58,150);\n"
"}\n"
"QPushButton:pressed{padding-top:2px;\n"
"padding-left:2px;}")
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.pushButton_start_test = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_start_test.setGeometry(QtCore.QRect(40, 640, 389, 61))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(22)
        self.pushButton_start_test.setFont(font)
        self.pushButton_start_test.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_start_test.setStyleSheet("QPushButton{\n"
"border:2px solid  rgba(68, 206, 246,150);\n"
"background-color: rgba(102, 204, 204,180);\n"
"border-radius:15px; \n"
"color: rgb(0, 51, 113);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:2px solid  rgba(14, 184, 58,150);\n"
"}\n"
"QPushButton:pressed{padding-top:2px;\n"
"padding-left:2px;}")
        self.pushButton_start_test.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_start_test.setObjectName("pushButton_start_test")
        self.pushButton_start_style = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_start_style.setGeometry(QtCore.QRect(20, 40, 191, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.pushButton_start_style.setFont(font)
        self.pushButton_start_style.setStyleSheet("QPushButton{\n"
"background-color: rgba(141, 75, 187,150);\n"
"border-radius:20px; \n"
"color: rgb(0, 51, 113);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));border:2px solid  rgba(14, 184, 58,150);\n"
"}\n"
"QPushButton:pressed{padding-top:2px;\n"
"padding-left:2px;}")
        self.pushButton_start_style.setObjectName("pushButton_start_style")
        self.pushButton_pause = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_pause.setGeometry(QtCore.QRect(230, 40, 211, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(18)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setStyleSheet("QPushButton{\n"
"background-color: rgba(141, 75, 187,150);\n"
"border-radius:20px; \n"
"color: rgb(0, 51, 113);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));border:2px solid  rgba(14, 184, 58,150);\n"
"}\n"
"QPushButton:pressed{padding-top:2px;\n"
"padding-left:2px;}")
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.pushButton_restart = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_restart.setGeometry(QtCore.QRect(110, 300, 111, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(14)
        self.pushButton_restart.setFont(font)
        self.pushButton_restart.setStyleSheet("QPushButton{\n"
"background-color: rgb(201, 55, 86);\n"
"border-radius:5px; \n"
"color: rgb(255, 201, 255);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{padding-top:1px;\n"
"padding-left:1px;}")
        self.pushButton_restart.setObjectName("pushButton_restart")
        self.lineEdit_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_input.setGeometry(QtCore.QRect(41, 129, 171, 24))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.lcdNumber_01 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_01.setGeometry(QtCore.QRect(240, 110, 191, 241))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        self.lcdNumber_01.setFont(font)
        self.lcdNumber_01.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lcdNumber_01.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px; \n"
"color: rgb(255, 33, 33);")
        self.lcdNumber_01.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_01.setLineWidth(1)
        self.lcdNumber_01.setDigitCount(2)
        self.lcdNumber_01.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_01.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_01.setProperty("value", 13.0)
        self.lcdNumber_01.setProperty("intValue", 13)
        self.lcdNumber_01.setObjectName("lcdNumber_01")
        self.label_Tips = QtWidgets.QLabel(self.groupBox_2)
        self.label_Tips.setGeometry(QtCore.QRect(40, 710, 381, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_Tips.setFont(font)
        self.label_Tips.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 85, 0);\n"
"")
        self.label_Tips.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Tips.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Tips.setObjectName("label_Tips")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 340, 111, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(201, 55, 86);\n"
"border-radius:5px; \n"
"color: rgb(255, 201, 255);}\n"
"QPushButton:hover{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 224, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{padding-top:1px;\n"
"padding-left:1px;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_submit.clicked.connect(MainWindow.save_data) # type: ignore
        self.pushButton.clicked.connect(MainWindow.slot_bt_show) # type: ignore
        self.pushButton_pause.clicked.connect(MainWindow.slot_pause) # type: ignore
        self.pushButton_start_style.clicked.connect(MainWindow.slot_start_video) # type: ignore
        self.pushButton_start_test.clicked.connect(MainWindow.slot_start_test) # type: ignore
        self.pushButton_restart.clicked.connect(MainWindow.slot_restart) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.slot_child) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能引体向上监测系统"))
        self.groupBox_2.setTitle(_translate("MainWindow", "操作界面"))
        self.groupBox.setTitle(_translate("MainWindow", "信息录入"))
        self.label_name.setText(_translate("MainWindow", "姓 名："))
        self.lineEdit_Name.setPlaceholderText(_translate("MainWindow", "输入姓名：何明洋"))
        self.label_proj.setText(_translate("MainWindow", "专 业："))
        self.lineEdit_Proj.setPlaceholderText(_translate("MainWindow", "输入专业：电信19-2班"))
        self.label_num.setText(_translate("MainWindow", "学 号："))
        self.lineEdit_Num.setPlaceholderText(_translate("MainWindow", "输入学号：2019022404"))
        self.label_infor_tips.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">*TextLabel</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "显示数字"))
        self.pushButton_submit.setText(_translate("MainWindow", "提       交"))
        self.pushButton_start_test.setText(_translate("MainWindow", "开 始 测 试"))
        self.pushButton_start_style.setText(_translate("MainWindow", "启动系统"))
        self.pushButton_pause.setText(_translate("MainWindow", "暂停测试"))
        self.pushButton_restart.setText(_translate("MainWindow", "重   置"))
        self.lineEdit_input.setText(_translate("MainWindow", "123"))
        self.label_Tips.setText(_translate("MainWindow", "*消息提醒"))
        self.pushButton_2.setText(_translate("MainWindow", "查看数据"))
import image_rc
